# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_n_features_vector <- function(feature_idx, n_nonzero_features_vector, offset, start_idx, end_idx) {
    invisible(.Call(`_ondisc_update_n_features_vector`, feature_idx, n_nonzero_features_vector, offset, start_idx, end_idx))
}

decrement_vector <- function(v) {
    invisible(.Call(`_ondisc_decrement_vector`, v))
}

add_value_to_vector <- function(v, to_add) {
    invisible(.Call(`_ondisc_add_value_to_vector`, v, to_add))
}

compute_cellwise_covariates <- function(n_umis, n_nonzero_features, p_mito, feature_w_max_expression, frac_umis_max_feature, feature_idx, j, x, mt_feature_idxs, start_idx, end_idx, feature_offset, cell_offset, n_cells, compute_n_umis, compute_n_nonzero_features, compute_p_mito, compute_feature_w_max_expression, compute_frac_umis_max_feature) {
    invisible(.Call(`_ondisc_compute_cellwise_covariates`, n_umis, n_nonzero_features, p_mito, feature_w_max_expression, frac_umis_max_feature, feature_idx, j, x, mt_feature_idxs, start_idx, end_idx, feature_offset, cell_offset, n_cells, compute_n_umis, compute_n_nonzero_features, compute_p_mito, compute_feature_w_max_expression, compute_frac_umis_max_feature))
}

write_to_csr <- function(file_name_in, start_idx, end_idx, feature_offset, cell_offset, n_features, f_row_ptr, feature_idx, m_j, m_x) {
    invisible(.Call(`_ondisc_write_to_csr`, file_name_in, start_idx, end_idx, feature_offset, cell_offset, n_features, f_row_ptr, feature_idx, m_j, m_x))
}

create_odm <- function(file_name_in, n_nonzero_features, feature_ids, n_cells, chunk_size, compression_level) {
    invisible(.Call(`_ondisc_create_odm`, file_name_in, n_nonzero_features, feature_ids, n_cells, chunk_size, compression_level))
}

load_row_cpp <- function(file_name_in, f_row_ptr, row_idx, n_cells) {
    .Call(`_ondisc_load_row_cpp`, file_name_in, f_row_ptr, row_idx, n_cells)
}

#' @title Read the dimension of the ODM into memory
#' @param file_name_in path to the odm file
read_dimension <- function(file_name_in) {
    .Call(`_ondisc_read_dimension`, file_name_in)
}

#' @title Read the feature IDs of an ODM into memory
#' @param file_name_in path to the odm file
#' @param n_features the number of features in the dataset
read_feature_ids <- function(file_name_in, n_features) {
    .Call(`_ondisc_read_feature_ids`, file_name_in, n_features)
}

#' @title Read the row pointer into memory
#' @param file_name_in path to the odm file
#' @param n_features the number of features in the dataset
read_row_ptr <- function(file_name_in, n_features) {
    .Call(`_ondisc_read_row_ptr`, file_name_in, n_features)
}

init_ull_vect <- function(size) {
    .Call(`_ondisc_init_ull_vect`, size)
}

print_ull_vect <- function(ull_vect) {
    invisible(.Call(`_ondisc_print_ull_vect`, ull_vect))
}

